### ISSUE TITLE
Any way to make thread id live between OpenAIClient instances? (assistants api)

### ISSUE THREAD

**Issue by lofti198** [higty/higlabo#106]
I currently experiment with assistants API. The code similar to your example here:
![image](https://github.com/higty/higlabo/assets/42960488/21f26378-d309-4db6-89c9-b9cbd515dc82)

I was supposing that thread id persistant between sessions. However, from my experiments - it is not. Maybe I miss something?

Why I need this? I want to put bug chunk of data (10k+ tokens) to the assistant and them ask him over this data. Just want to avoid putting context again and again. Or maybe you can suggest any other then assistant api way to do this? Even maybe with Claude instead of chat gpt?

**Comment by lofti198** [comment]
I guess, I already have the idea how to tackle this. I will be back with feedback

**Comment by higty** [comment]
OpenAI does not provide API to get thread_id list.
So, we must save thread id to our database.

It is missing of OpenAI
It looks good if an endpoint exists something like this.
GET https://api.openai.com/v1/assistant/{assistant_id}/threads
OpenAI's members are excellent, so I assume there's a reason for this.

regards.

**Comment by lofti198** [comment]
I tested and found that if we save internal thread id , we can get to the previous chat even from different OpenAiClient instances. Thank you for your cool package!

**Comment by lofti198** [comment]
By the way, is there anywhere example how to read results of processing after RunCreateAsync? I want to try it, since RunCreateStreamAsync still halucinates (after sending several big chunks of data)
