### ISSUE TITLE
The best way to find out Token Number

### ISSUE THREAD

**Issue by lofti198** [higty/higlabo#107]
Hi! I use this code (from your sample) to utilize ChatCompletionVision. How to find out how many tokens were used for the overal request? Thank you in advance!

```
private async ValueTask ChatCompletionVision()
        {
            var cl = OpenAIClient;

            var p = new ChatCompletionsParameter();

            var vMessage = new ChatImageMessage(ChatMessageRole.User);
            vMessage.AddTextContent("Please describe this image.");
            vMessage.AddImageFile(Path.Combine(Environment.CurrentDirectory, "Image", "Pond.jpg"));
            p.Messages.Add(vMessage);
            p.Model = "gpt-4o";
            p.Max_Tokens = 300;
            p.Stream = true;

            var result = new ChatCompletionStreamResult();
            await foreach (var text in cl.ChatCompletionsStreamAsync(p, result, CancellationToken.None))
            {
                Console.Write(text);
            }
            Console.WriteLine("");
            Console.WriteLine("■DONE");
        }
```

**Comment by higty** [comment]
Please see ChatCompletionStreamWithUsageResult method in OpenAIPlayground.cs file.
GetUsageResult method is key method.

```
var p = new ChatCompletionsParameter();
p.AddUserMessage($"How to enjoy coffee");
p.Model = "gpt-4o";
p.Stream_Options = new
{
    include_usage = true,
};

var result = new ChatCompletionStreamResult();
await foreach (string text in cl.ChatCompletionsStreamAsync(p, result, CancellationToken.None))
{
    Console.Write(text);
}
Console.WriteLine();
Console.WriteLine();

var usage = result.GetUsageResult();
if (usage != null)
{
    Console.WriteLine("------------------------");
    Console.WriteLine("Prompt tokne: " + usage.Prompt_Tokens);
    Console.WriteLine("Completion tokne: " + usage.Completion_Tokens);
    Console.WriteLine("Total tokne: " + usage.Total_Tokens);
}
```

**Comment by lofti198** [comment]
Thank you! It works awesome as always. By the way, have you research the question of price optimisation of image recognition? For example I have pretty typical documents which I recognize with gpt-o4 model. It costs usually like this:
_Prompt token: 1117
Completion token: 228
Total tokne: 1345_

Which way would you suggest me to go to optimise it? I guess training own image to text model (for typical layouts) is the best way?

**Comment by higty** [comment]
The best way to reduce price is to use local LLM.
You can get various model on HuggingFace and you can use it by ONNX from C#.
I think that LLM will be more intelligence in this year, so it it worth to watch.

**Comment by lofti198** [comment]
Oh great! Thank you for your cool hint on onnx!
