### ISSUE TITLE
OpenAI Assistant - Attaching a file not working

### ISSUE THREAD

**Issue by junsahagun** [higty/higlabo#109]
I am getting an error when attaching files to messages. OpenAI expects an object and but system is passing as a list of string.

**Comment by higty** [comment]
Hi.

What is the error that you are talking about?
Can you describe more detail about your error? Such as error log, reproduction code and so on.
I need more detail to solve your problem.

regards.

**Comment by higty** [comment]
I closed this issue because I could not reproduct without description.
