### ISSUE TITLE
Issue with the MessageCreateContent Class: Parameter Case Sensitivity

### ISSUE THREAD

**Issue by commercegenie** [higty/higlabo#112]
I've recently encountered an error while using the OpenAI library with the MessageCreateContent class. The error message states:

Error: "Missing required parameter: 'content[1].image_url'. You provided 'image_Url', did you mean to provide 'image_url'?"

This error occurs when I try to submit an image URL as part of a message prompt while setting the type to MessageCreateContent.Type. It seems that the OpenAI API only supports lowercase parameter names.

Here is the code snippet I believe it should be fixed:

public override string ToString()
{
    switch (this.Type)
    {
        case MessageCreateContentType.Text: return this.Text ?? "";
        case MessageCreateContentType.Image_File: return this.Image_File?.ToString() ?? "";
        case MessageCreateContentType.Image_Url: return this.Image_Url?.ToString() ?? "";
        default: throw new InvalidOperationException();
    }
}

It looks like we need to change Image_Url to image_url to match the case-sensitive requirements of the API. If anyone else is facing similar issues, make sure that all parameter names are in lowercase when working with the OpenAI API.

**Comment by higty** [comment]
Hi.
I will fix it in few days.
Please wait☺

**Comment by higty** [comment]
I fixed it.
I'll upload Nuget package in 24 hours.

**Comment by commercegenie** [comment]
Thanks for the quick response. Just tested it—it works perfectly!
