### ISSUE TITLE
Wrong Conversion of Special Characters

### ISSUE THREAD

**Issue by ArneVBNET** [higty/higlabo#13]
I found out that when a folder name contains one special character (i.e. löschen) ist not converted properly. The Problem is in 
function EncodeWithoutInsertingNewline(Byte[] input) 

on Line 156: startIndex += 3; 
This Line of Code must be set in the for loop under  c2 = input[startIndex + 2];

I fixed it.

[Base64Converter.zip](https://github.com/higty/higlabo/files/1600605/Base64Converter.zip)

**Comment by higty** [comment]
Hi, ArneVBNET.
Thank you for your post.
I modified code as you say and now updating all source code to .net standard 2.0 version.
I will finished it within a week.

regards.

**Comment by higty** [comment]
I fixed bug.
