### ISSUE TITLE
Enconding error

### ISSUE THREAD

**Issue by VladimirPobedinskiy** [higty/higlabo#14]
Wrong parse subject with text:
```=?utf-8?B?0J7RgtGH0ZHRgiDQviDQtNCy0LjQttC10L3QuNC4INCy0LDQ?=\r\n =?utf-8?B?s9C+0L3QvtCyINGBINGD0LPQu9GR0Lwg0JDQniAi0KHQuNCx0YPQs9C7?=\r\n =?utf-8?B?0LXQvNC10YIiINC90LAg0YLQtdGA0LzQuNC90LDQu9C1INCe0J7QniAi?=\r\n =?utf-8?B?0JLQodCaIg==?=\r\n```

![01](https://user-images.githubusercontent.com/198486/39901554-971e7b4c-550c-11e8-9ed7-8fd1405c9385.png)

**Comment by higty** [comment]
Hi.Thank you for your report.
Please describe about class you face exception.Is it SmtpClient or Pop3Client or ImapClient?

regards

**Comment by higty** [comment]
Thank you!
I what to know what text you expected if parse executed correctly.I will create test case with your problem.

regards

**Comment by VladimirPobedinskiy** [comment]
Correct text is
```Отчёт о движении вагонов с углём АО "Сибуглемет" на терминале ООО "ВСК"```

**Comment by higty** [comment]
OK.

I will investigate your problem.
Please wait for few days.

**Comment by higty** [comment]
It turned out a bug of Rfc2047Converter in HigLabo.Converter project.
I fixed and merge to master and upload new version of HigLabo.Converter.dll(2.0.1) to Nuget.

Please check it out.

**Comment by VladimirPobedinskiy** [comment]
Also need to remove whitespaces on start of line and end of line.

**Comment by VladimirPobedinskiy** [comment]
I download zip of repository and compile all. Then I copy all from ```d:\Projects\higlabo\HigLabo.Mail\bin\Release\_Net_4_5\``` 
to 
```<myproject>\Lib\HigLabo\```
and add references to it and try to debug project.

![screenshot 2018-05-22 001](https://user-images.githubusercontent.com/198486/40340158-e54c7c94-5dc0-11e8-8fb8-80f646bc79ff.png)

Message source text  (part):
![screenshot 2018-05-22 002](https://user-images.githubusercontent.com/198486/40340263-64921ef0-5dc1-11e8-8157-814edf321e51.png)

Text of message source (part):
```
Date: Thu, 17 May 2018 17:00:53 +1000
Subject: =?utf-8?B?0J7RgtGH0ZHRgiDQviDQtNCy0LjQttC10L3QuNC4INCy0LDQ?=
 =?utf-8?B?s9C+0L3QvtCyINGBINGD0LPQu9GR0Lwg0JDQniAi0KHQuNCx0YPQs9C7?=
 =?utf-8?B?0LXQvNC10YIiINC90LAg0YLQtdGA0LzQuNC90LDQu9C1INCe0J7QniAi?=
 =?utf-8?B?0JLQodCaIg==?=
Content-Type: multipart/mixed;
        boundary="--boundary_3_70629bba-946f-408a-8bed-32184fdc6853"
Message-ID: <f4364717-71fb-40ca-8e65-298dea9f1d1b@SRVMAIL.VICS.RU>
Received-SPF: fail
```

**Comment by VladimirPobedinskiy** [comment]
![compare](https://user-images.githubusercontent.com/198486/40340902-24a45a66-5dc5-11e8-84ab-04de3e3674f5.png)

**Comment by higty** [comment]
Hi.

I moved all library to .NET Core.I will not modify HigLabo in the future.
So, please get latest version of HigLabo.NetStandard from nder https://github.com/higty/higlabo.netstandard.

regards.
