### ISSUE TITLE
Check if mail is bounced

### ISSUE THREAD

**Issue by pmcfernandes** [higty/higlabo#15]
Hi

Very cool project. I like to know if is possible see is mail is bounced like aspose

    `  BounceResult bounced = mailMessage.CheckBounced();

        if (bounced.IsBounced == true)
        {
                 continue;
         }              `

**Comment by higty** [comment]
Hi.

Thank for comment.
Can you describe more detail about your requirement?

**Comment by pmcfernandes** [comment]
Hi,

Yes is very cool feature if you can add it to MailMessage class.

**Comment by higty** [comment]
Hi.

I spend a few hours and there is no specification whether the mail is bounced or not.
I found a library to detect bounced mail.
https://libsisimai.org

You can also add some extension method to MailMessage class like this.
```
public static class MailMessageExtensions
{
    public static bool CheckBounced(this MailMessage message)
    {
        //Your own logic for bounce mail or not...
    }
}
```

regards.
