### ISSUE TITLE
InvalidMimeFormatException was thrown

### ISSUE THREAD

**Issue by fabrypel** [higty/higlabo#2]
I find the bug in MimeStreamBuffer, occurs when the loaded buffer end with char 10 and call the ReadLine function ( this._Current goto this._End +1) and the IsEnd fail.
For fix change 
        public Boolean IsEnd()
        {
            return this._Current == this._End || _IsLastOfLine; 
        }
To
        public Boolean IsEnd()
        {
            return this._Current >= this._End || _IsLastOfLine; 
        }

**Comment by higty** [comment]
Hi fabrypel.
Thank you for your post.
I'll fix it in next release.
