### ISSUE TITLE
HigLabo.Mapper Can not Convert Array To List 

### ISSUE THREAD

**Issue by zhouandke** [higty/higlabo#39]
.Net 5 version, HigLabo.Mapper.Test add two test cases, fail

`        [TestMethod]
        public void ObjectMapper_ArrayProperty_ListProperty()
        {
            var mapper = new ObjectMapper();
            var src = new
            {
                Ids = new int[] { 1, 2, 3 }
            };
            var dst = new
            {
                Ids = new List<int>()
            };
            dst = mapper.Map(src, dst);
            Assert.AreEqual(src.Ids.Length, dst.Ids.Count);
            Assert.AreEqual(src.Ids[0], dst.Ids[0]);
            Assert.AreEqual(src.Ids[1], dst.Ids[1]);
            Assert.AreEqual(src.Ids[1], dst.Ids[1]);
        }

        [TestMethod]
        public void ObjectMapper_Array_List()
        {
            var mapper = new ObjectMapper();
            var src = new int[] { 1, 2, 3 };
            var dst = new List<int>();
            dst = mapper.Map(src, dst);
            Assert.AreEqual(src.Length, dst.Count);
            Assert.AreEqual(src[0], dst[0]);
            Assert.AreEqual(src[1], dst[1]);
            Assert.AreEqual(src[1], dst[1]);
        }`

**Comment by higty** [comment]
It does not support from value array to value list.
The "value" I say is Int16, Int32, Double, Decimal...etc.

But you can add your own custom mapping rule by AddPostAction method.
By using this feature, you can add any logic you want.

You can see sample in ObjectMapperTest.cs in HigLabo.Mapper.Test project.
ex)
        [TestMethod]
        public void ObjectMapper_Map_Flatten()
        {
            var mapper = new ObjectMapper();
            mapper.AddPostAction<User, UserFlatten>((source, target) =>
            {
                mapper.Map(source.Vector2, target);
                mapper.Map(source.MapPoint, target);
            });
            var u1 = new User();
            var u2 = mapper.Map(u1, new UserFlatten());

            Assert.AreEqual(u1.MapPoint.Latitude, u2.Latitude);
            Assert.AreEqual(u1.MapPoint.Longitude, u2.Longitude);
            Assert.AreEqual(u1.Vector2.X, u2.X);
        }

In this case, it may be

            var mapper = new ObjectMapper();
            mapper.AddPostAction<YourClassA, YourClassB>((source, target) =>
            {
                target.Ids.Clear();
                foreach (var item in source.Ids)
                {
                    target.Ids.Add(item);
                }
            });

I hope the number of class is not large. (Because it cause that you must add so many AddPostAction method...)

regards.

**Comment by zhouandke** [comment]
Thank for your suggestion.
I debug the code, it determines that array is ICollection, then use ICollection.Count property to loop, but runtime throw exception.
I think it can use Linq Count() method to get count, then use IEnumerable to loop, so this mapper support all IEnumerable like  HashSet LinkList。

By the way，I change to class type test，it fail too.
```
        [TestMethod]
        public void ObjectMapper_ArrayProperty_ListProperty()
        {
            var mapper = new ObjectMapper();
            var src = new
            {
                Ids = new TC0_Members[] { new TC0_Members() }
            };
            var dst = new
            {
                Ids = new List<TC0_Members>()
            };
            dst = mapper.Map(src, dst);
            Assert.AreEqual(src.Ids.Length, dst.Ids.Count);
        }
```

**Comment by higty** [comment]
Hi. Finally I have a time to fix these bug.
I will support it in .NET7. Please wait.

**Comment by higty** [comment]
I started to implement this issue.

**Comment by higty** [comment]
I passed your test.
I'll upload fixed version to Nuget in 24 hours.

**Comment by higty** [comment]
@zhouandke 
I fixed bug and upload Nuget package for .NET8.

**Comment by higty** [comment]
Hi!
I will copy .NET9.0 source to .NET standard and push it to Nuget.

**Comment by yasee** [comment]
Using HashSet<int> will cause an error.

```
public static void ToMapperTestDto(MapperTestDto to = null)
{
    ObjectMapper.Default.Map(srcObj, to ?? new MapperTestDto());
}

public class MapperTest
{
    public HashSet<int> Abc { get; set; } = new HashSet<int>();
}

public class MapperTestDto
{
    public HashSet<int> Abc { get; set; } = new HashSet<int>();
}
```

Error
```
ArgumentNullException: Value cannot be null.
Parameter name: indexer
System.Linq.Expressions.Expression.ValidateIndexedProperty (System.Linq.Expressions.Expression instance, System.Reflection.PropertyInfo indexer, System.String paramName, System.Collections.ObjectModel.ReadOnlyCollection`1[System.Linq.Expressions.Expression]& argList) (at <83ac8a1e73274b0997327421dd8896ad>:0)
System.Linq.Expressions.Expression.MakeIndexProperty (System.Linq.Expressions.Expression instance, System.Reflection.PropertyInfo indexer, System.String paramName, System.Collections.ObjectModel.ReadOnlyCollection`1[T] argList) (at <83ac8a1e73274b0997327421dd8896ad>:0)
System.Linq.Expressions.Expression.Property (System.Linq.Expressions.Expression instance, System.Reflection.PropertyInfo indexer, System.Collections.Generic.IEnumerable`1[T] arguments) (at <83ac8a1e73274b0997327421dd8896ad>:0)
System.Linq.Expressions.Expression.Property (System.Linq.Expressions.Expression instance, System.Reflection.PropertyInfo indexer, System.Linq.Expressions.Expression[] arguments) (at <83ac8a1e73274b0997327421dd8896ad>:0)
HigLabo.Core.ObjectMapper.CreateMapCollectionExpression (HigLabo.Core.ObjectMapper+MapParameter parameter, HigLabo.Core.ObjectMapper+CompileState state) (at <c74ba1e2094949e1ae3a066708986629>:0)
HigLabo.Core.ObjectMapper.CreateFunctionExpression (System.Type sourceType, System.Type targetType) (at <c74ba1e2094949e1ae3a066708986629>:0)
HigLabo.Core.ObjectMapper.CreateMapMethod (System.Type sourceType, System.Type targetType) (at <c74ba1e2094949e1ae3a066708986629>:0)
HigLabo.Core.ObjectMapper.Map[TSource,TTarget] (TSource source, TTarget target) (at <c74ba1e2094949e1ae3a066708986629>:0)
DotUnder.DtoMapper.ToMapperTestDto (DotUnder.DtoMapper+MapperTestDto to) (at Assets/MapperTest.cs:54)
```
