### ISSUE TITLE
Unable to open the saved image file

### ISSUE THREAD

**Issue by krishnankuppaswamy** [higty/higlabo#61]
@higty This is a great repo and an innovative way of generating code. Love this ❤️ 

I was trying to download the image and save it as PNG to disc. I am unable to get this working. Sample code is given below.

Note: Retrieving the same file content via Postman and saving it to disc as PNG is working; however not with the library.

### Sample code
```
    [Fact]
    public async Task ShouldSaveImage()
    {
        var client = Singleton.Instance.OpenAIClient;
        var fileId = "file-P2UVwnSXOTx3KOcS8S6WCxxx";
        var fileContentGetResponse = await client.FileContentGetAsync(fileId);
        WriteToImageFile(fileId, fileContentGetResponse.GetResponseBodyText());
    }

    private static void WriteToImageFile(string fileName, string content)
    {
        using FileStream fs = new($"{fileName}.png", FileMode.Create);
        byte[] imageBytes = Encoding.ASCII.GetBytes(content);
        fs.Write(imageBytes, 0, imageBytes.Length);
        fs.Flush();
    }
```

Expected image (saved via Postman)
![expected](https://github.com/higty/higlabo/assets/42537848/1d2d7fe0-68f3-46b5-a307-e012b3b9b539)

Actual image (saved via code above)
![actual](https://github.com/higty/higlabo/assets/42537848/ecac66bb-b5a6-4d01-8c36-b35c3d508375)

A quick help would be really helpful.

**Comment by higty** [comment]
Hi!
It seems bug.
Please wait for few days to fix it.

**Comment by higty** [comment]
I wonder that where your file_id come from?
I try test below code. Both fin-tune and assistant.

```csharp
var cl = OpenAIClient;
var p = new FileUploadParameter();
p.SetFile("Hig.png", File.ReadAllBytes("D:\\Data\\Dev\\Hig.png"));
p.SetPurpose(FilePurpose.Finetune);
var res = await cl.FileUploadAsync(p);
Console.WriteLine(res);

var fileResponse = await cl.FileContentGetAsync(res.Id);
File.WriteAllBytes("D:\\Data\\Dev\\Hig_Download.png", fileResponse.Stream!.ToByteArray());

```

But fine-tune does not allow image file(.png, .jpg...etc) 
Fine-tune only allow json format.

And when assistant, we can't download file. 

Please describe about your file_id to solve this problem.

regards.

**Comment by krishnankuppaswamy** [comment]
> I wonder that where your file_id come from?
> I try test below code. Both fin-tune and assistant.
> 
> ```csharp
> var cl = OpenAIClient;
> var p = new FileUploadParameter();
> p.SetFile("Hig.png", File.ReadAllBytes("D:\\Data\\Dev\\Hig.png"));
> p.SetPurpose(FilePurpose.Finetune);
> var res = await cl.FileUploadAsync(p);
> Console.WriteLine(res);
> 
> var fileResponse = await cl.FileContentGetAsync(res.Id);
> File.WriteAllBytes("D:\\Data\\Dev\\Hig_Download.png", fileResponse.Stream!.ToByteArray());
> 
> ```
> 
> But fine-tune does not allow image file(.png, .jpg...etc) 
> Fine-tune only allow json format.
> 
> And when assistant, we can't download file. 
> 
> Please describe about your file_id to solve this problem.
> 
> regards.
> 
> 

Thanks for taking a look into this.

It's via assistant. I was able to download the response via this library. However, the png format was not correct and hence the problem.

I am using the direct OpenAI API to download the image and that worked.

Helpful if you can review and provide a fix.

Thanks again.

**Comment by higty** [comment]
I think it is not allowed to get file via this API.
https://platform.openai.com/docs/api-reference/files/retrieve-contents

This is the error message.
```json
{
  "error": {
    "message": "Not allowed to download files of purpose: assistants",
    "type": "invalid_request_error",
    "param": null,
    "code": null
  }
}
```


I want to know the way you can download image file.
Is it possible to show me the detail that you can download image?

**Comment by higty** [comment]
![image](https://github.com/higty/higlabo/assets/10071037/ce4968ce-9d8a-4a6d-9d96-0a0a1b2cdd98)
I was upload via assistant.
I get file_id form right panel.
The file_id is "file-ShIMh9E6jz4PNdLjWk5VJHQA".

I tested below code.
```csharp
var fileResponse = await cl.FileContentGetAsync("file-ShIMh9E6jz4PNdLjWk5VJHQA");
File.WriteAllBytes("D:\\Data\\Dev\\Hig_Download.png", fileResponse.Stream!.ToByteArray());
```

I got exception. The response text is 
```json
{
  "error": {
    "message": "Not allowed to download files of purpose: assistants",
    "type": "invalid_request_error",
    "param": null,
    "code": null
  }
}
```

**Comment by krishnankuppaswamy** [comment]
Apologies for the delay in response. Thanks for taking a look into this.

I was wrong in stating these are assistant files. Agree that those can't be downloaded.

The file that I was trying to download was produced by the assistant and is part of `thread.message`

As I mentioned, I was able to download the file; but was unable to view the file.

I see Stream property added to the SDK. I will retest and confirm.

Meanwhile, if you can produce an image and try saving and confirm, that would help.

Thanks again!

**Comment by krishnankuppaswamy** [comment]
Apologies for the delay in response. Thanks for taking a look into this.

I was wrong in stating these are assistant files. Agree that those can't be downloaded.

The file that I was trying to download was produced by the assistant and is part of `thread.message`

As I mentioned, I was able to download the file; but was unable to view the file.

I see Stream property added to the SDK. I will retest and confirm.

Meanwhile, if you can produce an image and try saving and confirm, that would help.

Thanks again!

**Comment by krishnankuppaswamy** [comment]
Update: I am able to save the files generated by the assistant using the `Stream`

Thanks for the fix @higty :pray:

This issue can be closed now :)
