### ISSUE TITLE
Upload File Async Dropbox

### ISSUE THREAD

**Issue by ScottDWagner** [higty/higlabo#8]
I have been trying for quite awhile with the upload file async. You do not provide a example of this. also the normal upload file either fails or basically freezes up the machine that it is running on until the upload is finished and if this is a large file this can take sometime to complete. Can some one please provide a example of the the upload file Async please. I am new to this tech.

**Comment by higty** [comment]
Hi.

Can you show me your code that upload a file?
For example, WPF application with button1, a 10 lines code in button1_Click method.
I wil try to rewrite your code if I could have time.

**Comment by higty** [comment]
We stop to support Dropbox library.
