### ISSUE TITLE
Method not found: 'Boolean HigLabo.Core.ServerSentEventLine.IsEvent()

### ISSUE THREAD

**Issue by CrisDevMF** [higty/higlabo#83]
hi, 

Method not found: 'Boolean HigLabo.Core.ServerSentEventLine.IsEvent()

i'm facing this issue when calling RunCreateStreamAsync => GetStreamAsync => item.IsEvent()

it says it doesn't exist.

in this ServerSentEventLine struct, i actually can't see it.

I am using latest vession

Thanks in advance

**Comment by CrisDevMF** [comment]
Btw this library is amazing and so helpful. Thank you so much for it

**Comment by higty** [comment]
Thank you! I hope this library help your work!
Please update HigLabo.Core to latest version. It may solve your problem.

**Comment by CrisDevMF** [comment]
Super!!!! Thank you.

Yeah, it's definitely helpful.  

Also, i was looking int get  images/files they generate. Do you have this implemented?

Thanks in advance

**Comment by lofti198** [comment]
> Thank you! I hope this library help your work! Please update HigLabo.Core to latest version. It may solve your problem.

Hi! Installed the latest version just now. Getting the same error here:
![image](https://github.com/higty/higlabo/assets/42960488/7d7f2eed-ea0c-4b40-aa52-45c51fcafff2)

Code:
```
public static async Task Do()
{
    var cl = new OpenAIClient(Environment.GetEnvironmentVariable(Consts.ENV_VAR_OPEN_API_KEY));
    var assistantId = Consts.ASST_ID;
    var threadId = "";
    if (threadId.Length == 0)
    {
        var res = await cl.ThreadCreateAsync();
        threadId = res.Id;
    }
    {
        var p = new MessageCreateParameter();
        p.Thread_Id = threadId;
        p.Role = "user";
        p.Content = $"Hello! I want to know how to use OpenAI assistant API to get stream response.";
        var res = await cl.MessageCreateAsync(p);
    }
    {
        var p = new RunCreateParameter();
        p.Assistant_Id = assistantId;
        p.Thread_Id = threadId;
        p.Stream = true;
        var result = new AssistantMessageStreamResult();
        await foreach (string text in cl.RunCreateStreamAsync
                      (p, result, CancellationToken.None))
        {
            Console.Write(text);
        }
        Console.WriteLine();
        // You can get each server sent event value by these property.
        Console.WriteLine(JsonConvert.SerializeObject(result.Thread));
        Console.WriteLine(JsonConvert.SerializeObject(result.Run));
        Console.WriteLine(JsonConvert.SerializeObject(result.RunStep));
        Console.WriteLine(JsonConvert.SerializeObject(result.Message));
    }

}
```

Thank you in advance!

**Comment by higty** [comment]
I think it may be bug.
I'll upload new version within 12 hours.
Please wait.

Thank you for your detail investigation!

**Comment by higty** [comment]
I just upload latest version to Nuget.

**Comment by higty** [comment]
[OpenAISample_20240330.zip](https://github.com/higty/higlabo/files/14809173/OpenAISample_20240330.zip)
I confirmed this works perfectly.
Please check it out!!!

**Comment by lofti198** [comment]
It works! Great thank you for your job!!!
