### ISSUE TITLE
What is the best approach to add more context to the question

### ISSUE THREAD

**Issue by lofti198** [higty/higlabo#85]
I am building user support AI. I gave to the assistant basic knowledge about my product. Now when user asks some question the following algo happens:
1. system uses embeddings to fetch FAQ and other docs data somehow related to the question (lets call them "context")
2. I want to pass these fetched context along with original user request to assistant.

What is the best way to mark fetched data as additional context? Actually I can to that right into request or maybe send them as separate "system" roled message? Or what is the better way? If sending separate system message, how to send it both together with "user"-roled which I am sending now as below:

```  var messageCreateParams = new MessageCreateParameter
  {
      Thread_Id = internalThreadId,
      Role = "user",
      Content = userInput
  };
  await _client.MessageCreateAsync(messageCreateParams);```

**Comment by higty** [comment]
I think OpenAI recently added Additional_Messages property to 
https://api.openai.com/v1/threads/{thread_id}/runs
endpoint.
It may solve your issue.

I just released HigLabo.OpenAI verion 8.4.0.0 to Nuget.
It support temperature and additional_messages as well.

Let's try it!!!

**Comment by lofti198** [comment]
Thank you now its awesome! I will also experiment with per run instrucions and additional instructions for this purpose
![image](https://github.com/higty/higlabo/assets/42960488/22da6bc3-efe6-4d77-b176-67d653a2f180)

**Comment by higty** [comment]
@lofti198 
I'm looking forward to your feedback!

**Comment by lofti198** [comment]
Both parameters are working awesome! Exactly what I was searching for. You have done excellent job!

**Comment by higty** [comment]
That's great!
And your feedback also awsome!
