### ISSUE TITLE
Temperature support (recently added)

### ISSUE THREAD

**Issue by lofti198** [higty/higlabo#86]
Hi! OpenAI engineers just added temperature setup for assistant API. It would be cool if you can consider this paratemer in your library: https://community.openai.com/t/how-to-set-temperature-and-other-sampling-parameters-of-model-in-open-ai-assistant-api/486368/36?u=apris

Thank you in advance!

**Comment by higty** [comment]
Okey. I'll add it within 7 days.

You can inherit from ThreadRunParameter like MyThreadRunParameter class, and overrider GetRequestBody method like
```
        public override object GetRequestBody()
        {
            return new {
            	assistant_id = this.Assistant_Id,
            	thread = this.Thread,
            	model = this.Model,
            	instructions = this.Instructions,
            	tools = this.Tools,
            	metadata = this.Metadata,
            	stream = this.Stream,
            	top_n = 0.5,
            };
        }
```
And pass it to OpenAIClient object. It may work.

For your information, HigLabo.OpenAI also have a hook point to customize your request by PreSendRequest event in OpenAIClient class.

In the future, same thing may happen, you can cutomize your request to use latest API feature.

**Comment by lofti198** [comment]
Oh cool! I ll try it! Awesome library and awesome support!!!

p.s. do you have somewhere channel or blog where you describe what inspired you to create this library or in which projects do you use it yourself?

**Comment by higty** [comment]
I wrote article to CodeProject.
https://www.codeproject.com/Articles/5372480/Csharp-OpenAI-Library-that-Supports-Assistants-str

I also create Anthropic library that API is pretty much same as HigLabo.OpenAI.
https://www.codeproject.com/Articles/5379174/Csharp-Anthropic-Claude-Library-You-Can-Call-Claud

I have a X account. https://x.com/higlabo. Please follow me!

**Comment by higty** [comment]
I uploaded HigLabo.OpenAI version 8.4.0.0 that support temperature.
Please try it!

**Comment by lofti198** [comment]
> You can inherit from ThreadRunParameter like MyThreadRunParameter class, and overrider GetRequestBody method like GetRequestBody to setup lets say "instructions" - which temperature (from overriden method OR from properties) will have higher priority (I mean which will it use finally as a parameter)? Or if I setup parameter in properties, I just shouldnt use it in overriden method?

Cool! I really appreciate how fast you are! Btw, is there somewhere "Buy me a coffee" button? 

Now as far as I understand if the particular parameters is missing in API, I can try to pass it like this dynamic object. Just a question - lets say if I pass temperature throuhg your library properties but I also override
![image](https://github.com/higty/higlabo/assets/42960488/2c94fb01-4a0b-48a8-8d44-5170bdb58977)

**Comment by higty** [comment]
It depends on your requirement.
You can customize GetRequestBody method as you like.
OpenAIClient class will pass the returned object of GetRequestBody method as HTTP request body.

I don't have coffee button. I add it to my private backlog😊
