### ISSUE TITLE
Please update package dependencies

### ISSUE THREAD

**Issue by cdokolas** [higty/higlabo#9]
It appears that HigLabo.Mail v.1.0.2.4 has undeclared dependencies to HigLabo.Core and HigLabo.Converter. Installing HigLabo.Mail without also installing the mentioned dependencies causes failures when sending mail.

**Comment by higty** [comment]
Hi.

Sorry inconvenience.
Recently, I created a program named HigLabo.NugetManagementApplication on GitHub of HigLabo.That create .nupkg file automatically.Unfortunately, I could not have a time to find a way to automatically manage dependency and understand spec of nuspec file.So, I assume that developer who use my library must find a way to avoid error by adding HigLabo.Core,HigLabo.Converter from error message.
I'll modify this problem in the future but I could not a time to do it.

If you can help me, I think I only modify nuspec file to achieve your request.
For example, it is a HigLabo.Core.nuspec file.
`
<?xml version="1.0"?>
<package xmlns="http://schemas.microsoft.com/packaging/2012/06/nuspec.xsd">
  <metadata>
    <id>HigLabo.Core</id>
    <version>1.0.6.6</version>
    <authors>Higty</authors>
    <owners>Higty</owners>
    <projectUrl>https://github.com/higty/higlabo</projectUrl>
    <requireLicenseAcceptance>false</requireLicenseAcceptance>
    <description>HigLabo.Core provide core library and utility about String manupilation,type conversion,generic operator,Guid,Enum,...etc.</description>
    <copyright>Copyright © 2011- HigLabo All Rights Reserved</copyright>
    <tags>HigLabo.Core</tags>
    <dependencies>
      <group targetFramework=".NET Framework4.5">
        <dependency id="HigLabo.Converter" version="1.0.4.3" />
      </group>
    </dependencies>
  </metadata>
</package>
`
I don't know about
<group targetFramework=".NET Framework4.5">
is right?
<dependency id="HigLabo.Converter" version="1.0.4.3" />
how to write later version 1.0.4.3?
If you can tell me the right schema of dependency, I could modify it very short time.

Anyway, I'll modify dependencies failures if I could make a time to do it.
Please wait...

**Comment by cdokolas** [comment]
From the [dependency spedification](https://docs.microsoft.com/en-us/nuget/create-packages/dependency-versions#version-ranges), I think you need to use `(1.0.4.3,)` if you require versions later than 1.0.4.3 (but **not 1.0.4.3**).

**Comment by higty** [comment]
We all move to .NET standard, so close this issue.
