### ISSUE TITLE
Are you planning to add vector store usage for file search support?

### ISSUE THREAD

**Issue by lofti198** [higty/higlabo#90]
Hello! Cool news from OpenAI: https://platform.openai.com/docs/assistants/whats-new 

> We're launching an [improved retrieval tool called file_search](https://platform.openai.com/docs/assistants/tools/file-search), which can ingest up to 10,000 files per assistant - 500x more than before. It is faster, supports parallel queries through multi-threaded searches, and features enhanced reranking and query rewriting.
> Alongside file_search, we're introducing [vector_store objects](https://platform.openai.com/docs/assistants/tools/file-search/vector-stores) in the API. Once a file is added to a vector store, it's automatically parsed, chunked, and embedded, made ready to be searched. Vector stores can be used across assistants and threads, simplifying file management and billing.

Share, if you going to add vector stores support. Have a nice day! Thank you!

**Comment by higty** [comment]
Thank you for your inpformation.
Of cource, I'll add ths feature😊

**Comment by higty** [comment]
@lofti198 
I update Nuget package HigLabo.OpenAI 8.7.0.0 that support file search and vector store feature!

**Comment by lofti198** [comment]
> @lofti198 I update Nuget package HigLabo.OpenAI 8.7.0.0 that support file search and vector store feature!

Greatttttt! You are really  fast! Thank you!
