### ISSUE TITLE
RSS item should have multiple categories

### ISSUE THREAD

**Issue by lonix1** [higty/higlabo#94]
The RSS library extracts "category" in [RssItem_0_92.Category](https://github.com/higty/higlabo/blob/491b6d2a156040b197275b0d19a9613db613defb/NetStandard/HigLabo.Rss/Entity/0.92/RssItem_0_92.cs#L18). But an RSS item has multiple categories.

An example: https://www.nasa.gov/news-release/feed
The specification: https://cyber.harvard.edu/rss/rss.html#ltcategorygtSubelementOfLtitemgt

It should be: `public IEnumerable<RssCategory> Categories { get; set; }`

I think what it does now, it extract the first category found inside an item, and ignores the rest.

**Comment by higty** [comment]
@lonix1 
Thank you for your bug fix!
I'll integrate it to next version in few days.

regard.

**Comment by higty** [comment]
I fixed your report.
Thank you for your contribution!
