### ISSUE TITLE
RSS item should extract author from `<dc:creator>` element

### ISSUE THREAD

**Issue by lonix1** [higty/higlabo#95]
Another missing thing I found. The [RssItem_2_0.Author](https://github.com/higty/higlabo/blob/491b6d2a156040b197275b0d19a9613db613defb/NetStandard/HigLabo.Rss/Entity/2.0/RssItem_2_0.cs#L15) property is extracted from the `<author>` element [here](https://github.com/higty/higlabo/blob/491b6d2a156040b197275b0d19a9613db613defb/NetStandard/HigLabo.Rss/Entity/2.0/RssItem_2_0.cs#L52).

But many RSS feeds - especially those by Wordpress, which is probably the majority of RSS feeds - use the `<dc:creator>` element instead. Example feed [here](https://www.nasa.gov/news-release/feed).

I think it should be
```cs
Author = element.CastElementToString("author");
if (string.IsNullOrWhiteSpace(Author))
  Author = element.CastElementToString("[author](dc:creator)");
```

**Comment by higty** [comment]
Hi.Thank you for your contribution!
I fixed this and merge to master blanch.

regards

**Comment by higty** [comment]
Okey.
I'll port HigLabo.Rss to .NET8 and upload to Nuget.
Please wait few days.

**Comment by higty** [comment]
I just complete to port HigLabo.Rss to .NET7 and .NET8.
I also created nuget package.
HigLabo.Rss version 7.0.0.0 that work on .NET7 is now available!

**Comment by higty** [comment]
@lonix1 
I fixed bug and upload new nuget package.
Thank you for your bug fix!

**Comment by higty** [comment]
So, is this issue solved?

**Comment by higty** [comment]
Can you send me the xml file that cause error?

**Comment by higty** [comment]
I fixed bug and confirmed it work correctly on your xml file.

**Comment by migig** [comment]
And for me it is now working for .NET 8. Thank you for the fix.

Also, the new feature for extracting author is appreciated, because now it is showing me the author on so many feeds, and before it was showing nothing. Very big improvement!

**Comment by higty** [comment]
@lonix1 @migig 
Happly programing!
